import type { DataProduct, PublishGate } from '@/types/dataworks'

export const productFixture: DataProduct = {
  id: 'product-1',
  product_key: 'credit-insight',
  name_ko: 'Customer Credit Insight API',
  name_en: 'Customer Credit Insight API',
  short_name: 'Credit Insight',
  description: 'Credit insight product',
  executive_summary: '',
  sales_pitch: '',
  source_type: 'api',
  source_ref: 'FIN_TX',
  owner: 'data-team',
  allowed_teams: [],
  sensitivity: 'personal_credit',
  status: 'approved',
  version: 2,
  target_industries: ['fintech'],
  target_customers: ['lender'],
  pricing_model: 'usage',
  api_spec: '{}',
  poc_plan: '',
  risk_score: 82,
  revenue_score: 91,
  differentiation: '',
  similar_products: [],
  updated_by: 'admin',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-08-27T00:00:00Z',
}

export const blockedGateFixture: PublishGate = {
  product_key: productFixture.product_key,
  strict_gate: true,
  allowed: false,
  minimum_readiness: 70,
  required_approvals: ['data_owner', 'legal', 'compliance'],
  approval_status: { data_owner: 'approved', legal: 'pending', compliance: 'approved' },
  missing_approvals: ['legal'],
  missing_evidence: ['product_sla'],
  blocked_reasons: ['missing required approval: legal'],
  warnings: ['SLA targets are not configured'],
  asset_readiness: [{
    asset_key: 'FIN_TX',
    schema_score: 90,
    freshness_score: 88,
    sample_score: 80,
    missingness_score: 92,
    sensitivity_score: 75,
    external_sharing_score: 80,
    api_readiness_score: 90,
    billing_readiness_score: 76,
    overall_score: 84,
    notes: '',
    updated_by: 'admin',
    updated_at: '2026-08-27T00:00:00Z',
  }],
  checked_at: '2026-08-27T00:00:00Z',
  quality_passed: true,
  risk_reviewed: true,
  api_contract_configured: true,
  sla_configured: false,
  pricing_model_configured: true,
  masking_configured: true,
}
